scoreboard:
  title: '&4&lHidden Killer'
  preLobby:
    - '&7{date}'
    - ''
    - 'Jugadores: &a{counter}'
    - 'Mapa: &6{mapName}'
    - ''
    - '&emc.gameshidden.net'
  survival:
    - '&7{date}'
    - ''
    - 'Eres: {playerState}'
    - ''
    - 'Jugadores: &6{counter}'
    - 'Mapa: &6{mapName}'
    - 'Tiempo: &6{mapTime}'
    - ''
    - '&emc.gameshidden.net'
  killer:
    - '&7{date}'
    - ''
    - 'Eres: {playerState}'
    - 'Asesinatos: {playerKills}'
    - ''
    - 'Jugadores: &6{counter}'
    - 'Mapa: &6{mapName}'
    - 'Tiempo: &6{mapTime}'
    - ''
    - '&emc.gameshidden.net'