spawn:
  world: undefined
  x: 0
  y: 0
  z: 0
  yaw: 0
  pitch: 0

sign:
  - '&4&lHiddenKiller'
  - '&e{game}'
  - '{state}'
  - '{players}/{maxplayer}'

scoreboard:
  title: '&4&lHidden Killer'
  lobby:
    - ''
    - '&9&lNick: &7{username}'
    - '&9&lAsesinatos: &7{kills}'
    - '&9&lGanadas: &7{wins}'
    - '&9&lPerdidas: &7{losed}'
    - '&9&lJugadas: &7{played}'
    - ''
    - '&9&lLobby: &7{lobby}'
    - '&9&lPlayers: &7{players}'
    - ''
    - '&9&lHiddenCoins: &7'
    - ''
    - '&emc.gameshidden.net'
  preLobby:
    - '&7{date}'
    - ''
    - 'Jugadores: &a{counter}'
    - 'Mapa: &6{mapName}'
    - ''
    - '&emc.gameshidden.net'
  survival:
    - '&7{date}'
    - ''
    - 'Eres: {playerState}'
    - ''
    - 'Jugadores: &6{counter}'
    - 'Mapa: &6{mapName}'
    - 'Tiempo: &6{mapTime}'
    - ''
    - '&emc.gameshidden.net'
  killer:
    - '&7{date}'
    - ''
    - 'Eres: {playerState}'
    - 'Asesinatos: {playerKills}'
    - ''
    - 'Jugadores: &6{counter}'
    - 'Mapa: &6{mapName}'
    - 'Tiempo: &6{mapTime}'
    - ''
    - '&emc.gameshidden.net'